// support-workspace/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive, Router } from '@angular/router';
import { CommonModule, TitleCasePipe } from '@angular/common';
import { Subscription } from 'rxjs';
import { AuthService } from './core/services/auth.service';
import { ThemeService, Theme } from './core/services/theme.service';
import { User } from './core/models';
import { ToastContainerComponent } from './components/toast/toast-container.component';
import { CommandPaletteComponent } from './components/command-palette/command-palette.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive, CommonModule, TitleCasePipe, ToastContainerComponent, CommandPaletteComponent],
  template: `
    <app-toast-container></app-toast-container>
    <app-command-palette #cmdPalette></app-command-palette>

    <div [class.app-container]="isLoggedIn">
      <!-- Sidebar Navigation Console -->
      <aside class="sidebar" [class.mobile-open]="isMobileSidebarOpen" *ngIf="isLoggedIn">
        <div class="sidebar-header">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" fill="var(--color-accent)"/>
          </svg>
          <span class="brand-name">SupportDesk</span>
        </div>
        
        <nav class="sidebar-nav">
          <a routerLink="/dashboard" routerLinkActive="active" class="nav-item" (click)="closeMobileSidebar()">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="3" y="3" width="7" height="7"/>
              <rect x="14" y="3" width="7" height="7"/>
              <rect x="14" y="14" width="7" height="7"/>
              <rect x="3" y="14" width="7" height="7"/>
            </svg>
            <span>Tickets</span>
          </a>

          <!-- Workload summary node (Manager only) -->
          <a *ngIf="isManager" routerLink="/manager" routerLinkActive="active" class="nav-item" (click)="closeMobileSidebar()">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <line x1="18" y1="20" x2="18" y2="10"/>
              <line x1="12" y1="20" x2="12" y2="4"/>
              <line x1="6" y1="20" x2="6" y2="14"/>
            </svg>
            <span>Workload Analytics</span>
          </a>
        </nav>

        <div class="sidebar-footer">
          <div class="user-profile">
            <span class="avatar-circle">{{ userInitials }}</span>
            <div class="user-meta">
              <span class="user-name">{{ currentUser?.name }}</span>
              <span class="user-role">{{ currentUser?.role | titlecase }}</span>
            </div>
          </div>
        </div>
      </aside>

      <!-- Main Content Layout Pane -->
      <div [class.content-frame]="isLoggedIn">
        <header class="main-header heroui-glass-header" *ngIf="isLoggedIn">
          <div class="header-left" style="display: flex; align-items: center; gap: 0.5rem;">
            <button
              (click)="toggleMobileSidebar()"
              class="btn btn-secondary mobile-toggle-btn"
              aria-label="Toggle navigation menu"
              style="padding: 0.25rem 0.5rem; height: 32px;"
            >
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <line x1="3" y1="12" x2="21" y2="12"/>
                <line x1="3" y1="6" x2="21" y2="6"/>
                <line x1="3" y1="18" x2="21" y2="18"/>
              </svg>
            </button>
            <span class="page-title">Workspace Console</span>
          </div>
          <div class="header-right" style="display: flex; align-items: center; gap: 0.75rem;">
            <button
              (click)="cmdPalette.toggleModal()"
              class="btn btn-secondary"
              style="padding: 0.25rem 0.625rem; height: 32px; display: inline-flex; align-items: center; gap: 0.375rem; font-size: 0.8rem;"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="11" cy="11" r="8"/>
                <line x1="21" y1="21" x2="16.65" y2="16.65"/>
              </svg>
              <span>Search</span>
              <span class="heroui-kbd" style="color: var(--color-text-main); border-color: var(--color-border); background-color: var(--color-bg-base);">Ctrl+K</span>
            </button>
            <button
              (click)="toggleTheme()"
              class="btn btn-secondary"
              [attr.title]="currentTheme === 'light' ? 'Switch to Dark Mode' : 'Switch to Light Mode'"
              style="padding: 0.25rem 0.5rem; height: 32px; display: inline-flex; align-items: center;"
              aria-label="Toggle theme mode"
            >
              <svg *ngIf="currentTheme === 'light'" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="5" />
                <line x1="12" y1="1" x2="12" y2="3" />
                <line x1="12" y1="21" x2="12" y2="23" />
                <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
                <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
                <line x1="1" y1="12" x2="3" y2="12" />
                <line x1="21" y1="12" x2="23" y2="12" />
                <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
                <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
              </svg>
              <svg *ngIf="currentTheme === 'dark'" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
              </svg>
            </button>
            <button (click)="onLogout()" class="btn btn-secondary logout-btn">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>
                <polyline points="16 17 21 12 16 7"/>
                <line x1="21" y1="12" x2="9" y2="12"/>
              </svg>
              Logout
            </button>
          </div>
        </header>

        <div [class.main-viewport]="isLoggedIn">
          <router-outlet></router-outlet>
        </div>
      </div>
    </div>
  `
})
export class AppComponent implements OnInit, OnDestroy {
  isLoggedIn = false;
  isManager = false;
  isMobileSidebarOpen = false;
  currentUser: User | null = null;
  userInitials = '';
  currentTheme: Theme = 'light';
  private authSub?: Subscription;
  private themeSub?: Subscription;

  constructor(
    private authService: AuthService,
    private themeService: ThemeService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.authSub = this.authService.currentUser$.subscribe({
      next: (user) => {
        this.currentUser = user;
        this.isLoggedIn = !!user;
        this.isManager = this.authService.isManager();
        this.userInitials = user ? this.getInitials(user.name) : '';
      }
    });

    this.themeSub = this.themeService.currentTheme$.subscribe({
      next: (theme) => {
        this.currentTheme = theme;
      }
    });
  }

  ngOnDestroy(): void {
    if (this.authSub) {
      this.authSub.unsubscribe();
    }
    if (this.themeSub) {
      this.themeSub.unsubscribe();
    }
  }

  toggleTheme(): void {
    this.themeService.toggleTheme();
  }

  toggleMobileSidebar(): void {
    this.isMobileSidebarOpen = !this.isMobileSidebarOpen;
  }

  closeMobileSidebar(): void {
    this.isMobileSidebarOpen = false;
  }

  onLogout(): void {
    this.authService.logout();
    this.router.navigate(['/login']);
  }

  private getInitials(name: string): string {
    const parts = name.split(' ');
    if (parts.length >= 2) {
      return (parts[0][0] + parts[1][0]).toUpperCase();
    }
    return name.substring(0, 2).toUpperCase();
  }
}
export default AppComponent;


<!-- Template is now declared inline inside app.component.ts -->

// customer-portal/src/App.tsx
import React from 'react';
import { BrowserRouter, Routes, Route, Navigate, Link } from 'react-router-dom';
import { AuthProvider, useAuth } from './context/AuthContext';
import { ToastProvider } from './context/ToastContext';
import { ToastContainer } from './components/common/ToastContainer';
import { LoginForm } from './components/auth/LoginForm';
import { Dashboard } from './components/dashboard/Dashboard';
import { TicketForm } from './components/ticket/TicketForm';
import { TicketDetails } from './components/ticket/TicketDetails';
import { CommandPaletteModal } from './components/common/CommandPaletteModal';

// Route Guards
const ProtectedRoute: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { isAuthenticated, isLoading } = useAuth();

  if (isLoading) {
    return (
      <div className="container" style={{ padding: '4rem 2rem', textAlign: 'center' }}>
        <div className="skeleton" style={{ height: '40px', width: '200px', margin: '0 auto 2rem' }}></div>
        <div className="skeleton" style={{ height: '200px', width: '100%' }}></div>
      </div>
    );
  }

  if (!isAuthenticated) {
    return <Navigate to="/login" replace />;
  }

  return <>{children}</>;
};

const PublicOnlyRoute: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { isAuthenticated, isLoading } = useAuth();

  if (isLoading) {
    return (
      <div className="container" style={{ padding: '4rem 2rem', textAlign: 'center' }}>
        <div className="skeleton" style={{ height: '300px', width: '400px', margin: '0 auto' }}></div>
      </div>
    );
  }

  if (isAuthenticated) {
    return <Navigate to="/" replace />;
  }

  return <>{children}</>;
};

// Layout Component
const AppLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user, logout } = useAuth();
  const [isCmdOpen, setIsCmdOpen] = React.useState(false);
  const [theme, setTheme] = React.useState<'light' | 'dark'>(() => {
    return (localStorage.getItem('heroui_theme') as 'light' | 'dark') || 'light';
  });

  React.useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem('heroui_theme', theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => (prev === 'light' ? 'dark' : 'light'));
  };

  return (
    <div style={layoutStyles.wrapper}>
      <header className="heroui-glass-header" style={layoutStyles.header}>
        <div className="container" style={layoutStyles.headerContainer}>
          <Link to="/" style={layoutStyles.brand}>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" style={{ marginRight: '0.5rem' }}>
              <path d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM13 17H11V15H13V17ZM13 13H11V7H13V13Z" fill="var(--color-primary)"/>
            </svg>
            <strong>Customer Support Portal</strong>
          </Link>
          <div style={layoutStyles.userSection}>
            <button
              id="cmd-palette-trigger"
              onClick={() => setIsCmdOpen(true)}
              className="btn btn-secondary"
              style={{ padding: '0.25rem 0.625rem', height: '32px', display: 'inline-flex', alignItems: 'center', gap: '0.375rem', fontSize: '0.8rem' }}
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="11" cy="11" r="8" />
                <line x1="21" y1="21" x2="16.65" y2="16.65" />
              </svg>
              <span>Search</span>
              <span className="heroui-kbd">Ctrl+K</span>
            </button>

            <button
              onClick={toggleTheme}
              className="btn btn-secondary"
              title={theme === 'light' ? 'Switch to Dark Mode' : 'Switch to Light Mode'}
              style={{ padding: '0.25rem 0.5rem', height: '32px', display: 'inline-flex', alignItems: 'center' }}
              aria-label="Toggle theme mode"
            >
              {theme === 'light' ? (
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
                </svg>
              ) : (
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="12" cy="12" r="5" />
                  <line x1="12" y1="1" x2="12" y2="3" />
                  <line x1="12" y1="21" x2="12" y2="23" />
                  <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
                  <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
                  <line x1="1" y1="12" x2="3" y2="12" />
                  <line x1="21" y1="12" x2="23" y2="12" />
                  <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
                  <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
                </svg>
              )}
            </button>

            <span style={layoutStyles.userName}>{user?.name}</span>
            <button onClick={logout} className="btn btn-secondary" style={{ padding: '0.25rem 0.75rem', height: '32px' }}>
              Sign Out
            </button>
          </div>
        </div>
      </header>
      <CommandPaletteModal isOpen={isCmdOpen} onClose={() => setIsCmdOpen(false)} />
      <main className="container" style={layoutStyles.main}>
        {children}
      </main>
    </div>
  );
};

const layoutStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    backgroundColor: 'var(--color-bg-base)',
  },
  header: {
    padding: '0.875rem 0',
  },
  headerContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    textDecoration: 'none',
    color: 'var(--color-text-main)',
    fontSize: 'var(--font-size-base)',
  },
  userSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  userName: {
    fontSize: 'var(--font-size-sm)',
    fontWeight: '500',
    color: 'var(--color-text-main)',
  },
  main: {
    flex: 1,
    paddingTop: '2rem',
    paddingBottom: '2rem',
  },
};

export const AppContent: React.FC = () => {
  return (
    <BrowserRouter>
      <Routes>
        {/* Public Routes */}
        <Route
          path="/login"
          element={
            <PublicOnlyRoute>
              <LoginForm />
            </PublicOnlyRoute>
          }
        />

        {/* Protected Routes */}
        <Route
          path="/"
          element={
            <ProtectedRoute>
              <AppLayout>
                <Dashboard />
              </AppLayout>
            </ProtectedRoute>
          }
        />
        
        <Route
          path="/new-ticket"
          element={
            <ProtectedRoute>
              <AppLayout>
                <TicketForm />
              </AppLayout>
            </ProtectedRoute>
          }
        />

        <Route
          path="/ticket/:id"
          element={
            <ProtectedRoute>
              <AppLayout>
                <TicketDetails />
              </AppLayout>
            </ProtectedRoute>
          }
        />

        {/* Fallback Redirect */}
        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
    </BrowserRouter>
  );
};

const App: React.FC = () => {
  return (
    <AuthProvider>
      <ToastProvider>
        <ToastContainer />
        <AppContent />
      </ToastProvider>
    </AuthProvider>
  );
};

export default App;
